version: "3.8"

networks:
  dev:

services:
  gateway:
    build:
      context: gateway/docker/nginx
    ports:
      - "8082:8082"
      - "8081:8081"
    depends_on:
      - fast-api
      - frontend-node
    container_name: "nginx"
    volumes:
      - frontend-dist:/app:ro
    networks:
      - dev

  fast-api:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: app
      CREDENTIALS_GOOGLE: /run/secrets/credentials.json
      FRONTEND_URL: http://localhost:8082
    ports:
      - "8080:8080"
    depends_on:
      - api-postgres
    networks:
      - dev

  frontend-node:
    build:
      context: ./frontend
      dockerfile: docker/prod/Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    volumes:
      - ./frontend:/app
      - frontend-dist:/app/dist
    tty: true
    networks:
      - dev

  api-postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - rs-database:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - dev

secrets:
  credentials:
    file: ./backend/credentials.json

volumes:
  rs-database:
  frontend-dist:
