version: '3.8'

networks: 
  dev:

services:
  frontend-node:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - dev

  fast-api: 
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      FRONTEND_URL: http://frontend-node:5173
    ports:
      - "8000:8000"
    networks:
      - dev