"""empty message

Revision ID: 889af8cf3312
Revises: 8b676d9ea9c3
Create Date: 2025-04-08 14:37:43.362528

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "889af8cf3312"
down_revision: Union[str, None] = "8b676d9ea9c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("datetime", sa.DateTime(), nullable=False))
    op.add_column("events", sa.Column("details", sa.Text(), nullable=True))
    op.alter_column("events", "description", existing_type=sa.TEXT(), nullable=False)
    op.drop_constraint("uq_events_guid", "events", type_="unique")
    op.drop_column("events", "time")
    op.drop_column("events", "time_of_the_event")
    op.drop_column("events", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "events",
        sa.Column(
            "time_of_the_event",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "events",
        sa.Column("time", postgresql.TIME(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("uq_events_guid", "events", ["guid"])
    op.alter_column("events", "description", existing_type=sa.TEXT(), nullable=True)
    op.drop_column("events", "details")
    op.drop_column("events", "datetime")
    # ### end Alembic commands ###
