"""empty message

Revision ID: fccf22af9d7a
Revises: 6409025812b7
Create Date: 2025-04-09 03:41:46.598849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fccf22af9d7a"
down_revision: Union[str, None] = "6409025812b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "participants", sa.Column("payment", sa.Integer(), nullable=False)
    )
    op.add_column(
        "participants", sa.Column("prepayment", sa.Float(), nullable=False)
    )
    op.add_column(
        "participants", sa.Column("people_count", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("participants", "people_count")
    op.drop_column("participants", "prepayment")
    op.drop_column("participants", "payment")
    # ### end Alembic commands ###
